;;;;;; Sandbox Profile Language prelude

;;; SBPL library functions

;; param -- get the value of a compile-time parameter, or false if undefined
(define (param key)
  (let ((value (assoc key *params*)))
    (and value (cdr value))))

;; regex-quote -- quote a string so it's interpreted literally in a regex
(define (regex-quote s)
  (if (not (string? s))
      (error "argument to regex-quote must be a string"))
  (define special "^.[$()|*+?{\\")
  (let helper ((s s)
               (r ""))
    (if (equal? 0 (string-length s))
        r
        (helper (substring s 1)
                (let ((c (substring s 0 1)))
                  (if (internal-strchr special (string-ref c 0))
                      (string-append r "\\" c)
                      (string-append r c)))))))

;; path-literal -- interpret the path in a UNIX domain filter literally
(define (path-literal s)
  (string-append "^"
                 (regex-quote s)
                 "$"))

;;; System constants

(define __DARWIN_NSIG 32)
(define SIGHUP 1)
(define SIGINT 2)
(define SIGQUIT 3)
(define SIGILL 4)
(define SIGTRAP 5)
(define SIGABRT 6)
(define SIGPOLL 7)
(define SIGIOT SIGABRT)
(define SIGEMT 7)
(define SIGFPE 8)
(define SIGKILL 9)
(define SIGBUS 10)
(define SIGSEGV 11)
(define SIGSYS 12)
(define SIGPIPE 13)
(define SIGALRM 14)
(define SIGTERM 15)
(define SIGURG 16)
(define SIGSTOP 17)
(define SIGTSTP 18)
(define SIGCONT 19)
(define SIGCHLD 20)
(define SIGTTIN 21)
(define SIGTTOU 22)
(define SIGIO 23)
(define SIGXCPU 24)
(define SIGXFSZ 25)
(define SIGVTALRM 26)
(define SIGPROF 27)
(define SIGWINCH 28)
(define SIGINFO 29)
(define SIGUSR1 30)
(define SIGUSR2 31)

(define SOCK_STREAM 1)
(define SOCK_DGRAM 2)
(define SOCK_RAW 3)
(define SOCK_RDM 4)
(define SOCK_SEQPACKET 5)
(define AF_UNSPEC 0)
(define AF_UNIX 1)
(define AF_LOCAL AF_UNIX)
(define AF_INET 2)
(define AF_IMPLINK 3)
(define AF_PUP 4)
(define AF_CHAOS 5)
(define AF_NS 6)
(define AF_ISO 7)
(define AF_OSI AF_ISO)
(define AF_ECMA 8)
(define AF_DATAKIT 9)
(define AF_CCITT 10)
(define AF_SNA 11)
(define AF_DECnet 12)
(define AF_DLI 13)
(define AF_LAT 14)
(define AF_HYLINK 15)
(define AF_APPLETALK 16)
(define AF_ROUTE 17)
(define AF_LINK 18)
(define pseudo_AF_XTP 19)
(define AF_COIP 20)
(define AF_CNT 21)
(define pseudo_AF_RTIP 22)
(define AF_IPX 23)
(define AF_SIP 24)
(define pseudo_AF_PIP 25)
(define AF_NDRV 27)
(define AF_ISDN 28)
(define AF_E164 AF_ISDN)
(define pseudo_AF_KEY 29)
(define AF_INET6 30)
(define AF_NATM 31)
(define AF_SYSTEM 32)
(define AF_NETBIOS 33)
(define AF_PPP 34)
(define pseudo_AF_HDRCMPLT 35)
(define AF_RESERVED_36 36)
(define AF_IEEE80211 37)
(define AF_UTUN 38)
(define AF_MAX 40)
